name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar Archivos
        uses: actions/checkout@v4

      #      - uses: amondnet/vercel-action@v25 #deploy
      #        with:
      #          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
      #          vercel-args: "--prod" #Optional
      #          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
      #          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
      #working-directory: ./sub-directory

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          #PREBUILT: true
